Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.serverless.handler.CreateChairHandler
      CodeUri: C:\project\demo_aws_java\aws-java-chairs-api
      Runtime: java8
      Architectures:
        - x86_64